embedly:
  build: ./embedly
  env_file: .env
  links:
    - redis
  expose:
    - "7001"
  restart: always

nginx:
  build: ./nginx
  links:
    - embedly
  ports:
    - "80:80"
  restart: always

redis:
  image: redis
